-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.books
(
    idbook serial,
    libro  character varying(100),
    precio decimal(3,2) not null,
    PRIMARY KEY (idbook)
);

CREATE TABLE IF NOT EXISTS public.categorias
(
    idcategory serial,
    categoria character varying(50),
    PRIMARY KEY (idcategory)
);

CREATE TABLE IF NOT EXISTS public.authors
(
    idauthor serial,
    autor character varying(100),
    PRIMARY KEY (idauthor)
);

CREATE TABLE IF NOT EXISTS public.bookscategories
(
    idbookscategories serial,
    bookid serial,
    categoryid serial,
    PRIMARY KEY (idbookscategories)
);

CREATE TABLE IF NOT EXISTS public.booksauthors
(
    idbooksauthors serial,
    bookid serial,
    authorid serial,
    PRIMARY KEY (idbooksauthors)
);

CREATE TABLE IF NOT EXISTS public.ventas
(
    idventas serial,
    bookid serial,
    libro character varying(100),
    valor decimal(3,2) not null,
    PRIMARY KEY (idventas)
);

ALTER TABLE public.booksauthors
    ADD FOREIGN KEY (bookid)
    REFERENCES public.books (idbook)
    NOT VALID;


ALTER TABLE public.booksauthors
    ADD FOREIGN KEY (authorid)
    REFERENCES public.authors (idauthor)
    NOT VALID;


ALTER TABLE public.bookscategories
    ADD FOREIGN KEY (bookid)
    REFERENCES public.books (idbook)
    NOT VALID;


ALTER TABLE public.bookscategories
    ADD FOREIGN KEY (categoryid)
    REFERENCES public.categorias (idcategory)
    NOT VALID;


ALTER TABLE public.ventas
    ADD FOREIGN KEY (bookid)
    REFERENCES public.books (idbook)
    NOT VALID;

END;